### ISSUE TITLE
CGIエグゼキュータの特定

### ISSUE THREAD

**Issue by corvvs** [corvvs/webserv#116]
webservの課題の制約により、CGIはスクリプトファイルを`execve`に直渡しするのではなく、
ファイルの種類ごとにエグゼキュータを指定する必要がある。
よって以下の情報が必要になる。

- ファイルパスから言語を特定する。
- 言語からエグゼキュータを特定する。

「言語」を間に挟まず「ファイルパスからエグゼキュータを特定する」でもいいかも。

**Comment by corvvs** [comment]
## yokawada提案

### サーバの起動前フェーズ

CGI対応する言語ごとにデフォルトのエグゼキュータを探す。

### confパースフェーズ

confに言語ごとのエグゼキュータを指定する独自ディレクティブを用意しておき、confパース時にそれをパースする。

### リクエスト処理フェーズ

1. ファイルパス, 特にファイル拡張子から「言語」(ruby, PHP, pythonなど)を特定する。
2. 得られた「言語」のエグゼキュータが判明しているなら、エグゼキュータを設定。そうでないなら500エラー。

**Comment by ryo-manba** [comment]
[質問]
1. サーバー起動前フェーズって、a.outを実行前段階で調べておくって話ですか？

2. confのパースは以下の認識であってますか？
```
# config
ruby_path /usr/bin/ruby;

# 処理
map[".rb"] = "/usr/bin/ruby";
```

```
curl localhost:80/test.rb

executer = map[".rb"];
cgi_path "/test.rb";
```

**Comment by corvvs** [comment]
1.
質問の意図があんまりわかってないです。
a.outとは何をさしてる？

2.
大体そうなると思います。
ディレクティブは、言語とパスをそれぞれ指定する形がよさそう。
（言語に依存しない名前にする）

**Comment by ryo-manba** [comment]
> CGI対応する言語ごとにデフォルトのエグゼキュータを探す。

の意味がわかってないです

**Comment by corvvs** [comment]
C言語などのようにコンパイルされた実行ファイルを単独で実行するような言語はCGI対応できないことになると思います。
（これはwebservの課題制約のせい。ピカチュウtimesも参照のこと。）

**Comment by ryo-manba** [comment]
configでエグゼキューターに対応するパスを指定するのものだと思ったんですけど、
その場合、デフォルトのエグゼキュータを探す処理って必要なくないですか？

`cgi_path .rb /usr/bin/ruby;`
そのまま対応するpathをエグゼキューターとして使うだけ。みたいなイメージでいます。

**Comment by corvvs** [comment]
必要はないですが、phpやpythonくらいは探しておいてあげてもいいような気はします。

**Comment by ryo-manba** [comment]
- ディレクティブなしで、対応するエグゼキューターはすべて事前に探す
- configで指定されたものだけを使用する

のどちらか1つに絞ってもいい気がしますね。

例えばデフォルトでpythonのエグゼキュータを見つけても、configにpythonのルールが書いてあったときに、
どっちを使うかっていう余計な条件分岐が増えそうだと思いました。

**Comment by corvvs** [comment]
conf優先で特に紛れがないと思います。

**Comment by corvvs** [comment]
↑confのほうを残す形で辞書をマージすればよい、という意味です
