### ISSUE TITLE
ソケットを介しないwriite, readの後でerrnoをみてもいいのだろうか

### ISSUE THREAD

**Issue by corvvs** [corvvs/webserv#142]
タイトルの通り。

「ソケットを介しないwriite, read」とはつまりファイルアクセスのこと。

これらの場合は監視関数もかまさない。

**Comment by corvvs** [comment]
よくみたらerrnoみてるのってopenとかunlinkとかstatの後だけで、
read, writeの時は見てなかったわ・・・

**Comment by ryo-manba** [comment]
戻り値で確認できちゃいますもんね。このissueはcloseで大丈夫ですかね？

**Comment by corvvs** [comment]
今日のミーティングまでは開けておきましょう・・・何か思いつくことがあるかもしれないので。
