### ISSUE TITLE
`path_local`の仕様ミス

### ISSUE THREAD

**Issue by corvvs** [corvvs/webserv#174]
https://wiki.suikawiki.org/n/SCRIPT_NAME

> [SCRIPT_NAME](https://wiki.suikawiki.org/n/SCRIPT_NAME) は[CGIスクリプト](https://wiki.suikawiki.org/n/CGI%E3%82%B9%E3%82%AF%E3%83%AA%E3%83%97%E3%83%88)を識別する [URL](https://wiki.suikawiki.org/n/URL) の [path](https://wiki.suikawiki.org/n/path) ([パーセント符号化](https://wiki.suikawiki.org/n/%E3%83%91%E3%83%BC%E3%82%BB%E3%83%B3%E3%83%88%E7%AC%A6%E5%8F%B7%E5%8C%96)されていないもの) を設定しなければ[なりません](https://wiki.suikawiki.org/n/%E3%81%AA%E3%82%8A%E3%81%BE%E3%81%9B%E3%82%93)。

## to be

```
http {
    server {
        listen 80;
        listen 8080;
        server_name "server1";
        location / {
            exec_cgi on;
            root /Users/corvvs/reps/42cursus/webserv/;
            index index.html index.htm;
        }
    }
}
```

という`conf`があり,
パス`/Users/corvvs/reps/42cursus/webserv/cgi.rb` にCGIスクリプトがあり,
リクエストターゲットが`/cgi.rb/path/to`だった場合,

- **`path_local`は`/cgi.rb`**
- `path_after`は`/path/to`

であるべき。

## as is

- **`path_local`は`/Users/corvvs/reps/42cursus/webserv/cgi.rb`**
- `path_after`は`/path/to`

となっている。

`path_after`は合ってるが`path_local`がちょっと違う。

## 要望

`path_local`にリクエストターゲットより上の部分(=`root`?)が入らないようにして欲しい。

**Comment by corvvs** [comment]
「仕様ミス」というのはつまり僕がお願いする内容を間違えたという意味です。

**Comment by ryo-manba** [comment]
https://tex2e.github.io/rfc-translater/html/rfc3875.html

> The SCRIPT_NAME string forms some leading part of the path component of the Script-URI derived in some implementation-defined manner. 

たしかに。SCRIPT_NAMEは先頭部分を指すみたいですね

**Comment by ryo-manba** [comment]
ってなると、

```
/Users/corvvs/reps/42cursus/webserv/cgi.rb 

path_cgi_root: /Users/corvvs/reps/42cursus/webserv/
path_local: /cgi.rb
```

みたいにすればいいですかね？
新しくメンバ増やして

**Comment by corvvs** [comment]
あ、そうですね。

**Comment by ryo-manba** [comment]
```c++
    struct CgiResource {
        HTTP::byte_string root;
        HTTP::byte_string script_name;
        HTTP::byte_string path_info;
    };
```
という構造体で管理する
