### ISSUE TITLE
[config] 空のファイルを弾くようにする

### ISSUE THREAD

**Issue by ryo-manba** [corvvs/webserv#201]
#### 概要
パーサーで弾いてなかったので、イベントループが回り続けることになっていた。

**Comment by corvvs** [comment]
confファイルが空だと問題が起きるということ？
それとも空のファイルに対するリクエストで問題が起きるということ？

**Comment by ryo-manba** [comment]
webservを実行すると無限ループになるのが問題かと思いました。(listenなどせずにイベントループが回り続ける)

**Comment by corvvs** [comment]
前者ってことですね。了解です。
