### ISSUE TITLE
CGIスクリプトが空の場合に無限ループする

### ISSUE THREAD

**Issue by ryo-manba** [corvvs/webserv#229]
#### 概要
- `./cgi/ruby/blank.rb` を呼ぶと無限ループしている。
- ヘッダーがない場合というのが適切かも

```
> curl localhost:8087/cgi/ruby/blank.rb  
<html>
<head>
<title>webserv error</title>
  <style>
    .error-page {
      font-size: x-large;
      text-align: center;
    }
  </style>
</head>
</body>
<h3 class="error-page">408 roundtrip timed out</h3>
<hr>
</body></html>
```

**Comment by ryo-manba** [comment]
ヘッダーがないことが原因かもしれない

以下でも無限ループしている。
```ruby
# puts "Content-type: text/html\n\n"
puts "<html><body>Hello World</body></html>"
```

**Comment by ryo-manba** [comment]
> Every CGI script must print a header line, which the server uses to build the full HTTP headers of its response. If your CGI script produces invalid headers or no headers, the web server will generate a valid response for the client -- generally a 500 Internal Server Error message. docstore.mik.ua/orelly/linux/cgi/ch03_03.htm

CGIスクリプトがヘッダーを生成しない場合は、500エラーを返しちゃっていいのかも。

https://docstore.mik.ua/orelly/linux/cgi/ch03_03.htm#:~:text=If%20your%20CGI%20script%20produces,should%20return%20only%20partial%20headers.

**Comment by ryo-manba** [comment]
ヘッダーの終わりが来なかったら500エラーを返す。

**Comment by corvvs** [comment]
なかなか顕在化しにくいけどHTTPリクエストにも実は同じ問題が隠れていそう。
