### ISSUE TITLE
configのパーサーとHTTPサーバーの連携

### ISSUE THREAD

**Issue by ryo-manba** [corvvs/webserv#61]
### 概要
configのパーサーとHTTPサーバーを連携したい。
その実装方針と問題点についてまとめた。

### 問題点
---

listenディレクティブの数だけlisten関数を呼び出すと、以下の場合にbindが失敗する。

```
server {
	listen 80;
	server_name "srv1";
}
server {
	listen 80; # 異なるサーバーコンテキストで全く同じlistenの情報を持っている
	server_name "srv2";
}
```
そのため重複しているlistenの情報は、事前にまとめる必要がある。

### 対応案
--- 
1つのChannel対して、Configの配列(list)を持たせる。(`Chanel(1) -> Config(多)`)
そうすることで、`server_name`などの指定がない場合は、
先頭のConfigを利用して、HTTPリクエストのルーティングを行うことができる。

```
例)
server { listen 80; } # port80へのアクセスは上の情報を使う(指定がない場合)
server { listen 80; }
server { listen 81; }
```
上記の例だと
- 80のChannelがconfigを2つ持つ
- 81のChannelがconfigを1つ持つ

**実装**
すでにbind済みのportが来たら、Channelが持つConfigの配列にpush_backするだけでいい。(おそらく)

#### その他
HTTPリクエストの処理フロー(現状のイメージ)
1. リクエストから適切なconfig(Serverコンテキスト)を見つける。
2. リクエストターゲットを元に適切なLocationコンテキストを見つける。
3. ルーティングに必要な情報をLocationコンテキストから取得する。
4. ルーティングの情報を元にリソースを取得する。

関連issue #7

**Comment by corvvs** [comment]
>  そうすることで、server_nameなどの指定がない場合は、
(念の為注釈) `default_server`指定がある場合はこの限りではない、はず。

> 1. リクエストから適切なconfig(Serverコンテキスト)を見つける。

Channel, およびChannelから生成されたConnectionは必然的にある1つのlistenに対応しているので、
そのlistenが持つ「Configの配列」から探せばよい。

**Comment by corvvs** [comment]
(一応補足)

1つのserverが異なる複数のlistenを持つこともある。
(同じlistenを持つときはconfigのエラー)
