### ISSUE TITLE
HTTPエラーと持続的接続

### ISSUE THREAD

**Issue by corvvs** [corvvs/webserv#85]
## タスク

- [x] 正常に終了するリクエストを、接続を切らずに連続して処理できる
- [x] 正常に終了するリクエストを処理したあと、データを送らない場合に接続がタイムアウトする
- [x] 正常に終了するリクエストを2つ繋げて送信した時、レスポンスが2つ連続で返ってくる
- [ ] recoverable(回復可能)エラーについて
    - 以下にあてはまるエラーを"recoverableエラー"とする:
        - リクエストのヘッダ解析完了までに生じたエラーの中で、そのまま次のリクエストを処理することが可能かつそうしても支障がないもの
        - リクエストマッチングで生じたもの
    - 上記に当てはまらないエラーは"unrecoverableエラー"とし、例外を投げることで対処する。
    - [x] ルーティング時にリクエストがrecoverableエラーを抱えている場合, ルーティングを行わずデフォルトのエラーページに対する`FileReader`オリジネータを生成する。
    - [ ] リクエストマッチング結果がrecoverableエラーを抱えている場合, エラーページに対する`FileReader`オリジネータを生成する。

## テーマ

- ラウンドトリップの途中でHTTPエラー例外が投げられた時、処理フローはどう変わるか？
- あるリクエストがHTTPエラーを引き起こすとして、HTTP接続を持続させられるのはどのような時か？

**Comment by corvvs** [comment]
### ラウンドトリップ途中のHTTPエラー

`Connection::notify`がHTTPエラーをキャッチした場合。

必要事項をメモってみる。

- エラーレスポンス送信中に発生したHTTPエラーは回復不能とみなし、`Connection`を終了させる。
- エラーレスポンス送信中は、通常のレスポンス送信と同じ扱いとする:
  - リクエストへのデータ注入を行わない

**Comment by corvvs** [comment]
## 持続可能なHTTPエラー

HTTPエラーを「HTTP通信を持続可能なもの」(**持続可能エラー**)とそうでないものに分類する。
HTTPエラーが持続可能である条件は何か？

- レスポンス送信開始前に発生したものであること
  - 従って通信系のエラーは基本的に持続可能でないはず
- リクエストの終端を確定する障害にならないこと

**Comment by corvvs** [comment]
## HTTPリクエストの長さ

https://wiki.suikawiki.org/n/%E3%83%A1%E3%83%83%E3%82%BB%E3%83%BC%E3%82%B8%E6%9C%AC%E4%BD%93
を再解釈。リクエストの場合のみ。

1. `Transfer-Encoding:`が存在して、かつ最後の値が`chunked` -> chunked符号化で決まる。
2. `Transfer-Encoding:`が存在して、かつ最後の値が`chunked`でない -> **Bad Request** かつ**接続を閉じる**。
  - メッセージの長さを決められない = 次のメッセージの開始位置を決められない = 接続を閉じるしかない
3. `Transfer-Encoding:`が存在せず、かつ`Content-Length:`が妥当でない状態の場合 ->  **Bad Request** かつ**接続を閉じる**。
4. `Transfer-Encoding:`が存在せず、かつ`Content-Length:`が妥当である場合 ->  `Content-Length:`で決まる
5. その他 -> 本文の長さは0.

**Comment by corvvs** [comment]
そろそろ固めねば。

**Comment by corvvs** [comment]
もう一度考え直す。
持続不可能(=回復不能?)なエラーとは。

その前に「持続不可能」であることとは何か。
「持続」的接続は、同一のHTTP接続で複数のHTTPリクエストとハンドルすること。
従って、**異なるHTTPリクエストの境界をreasonableに特定できない**と持続的接続が実現できないことになる。

もう1つ、レスポンスの送信中に起きたエラーは、持続可能でなくなる。

### 「異なるHTTPリクエストの境界をreasonableに特定できな」くなるエラーとは

- 通信に関するエラー
    - タイムアウト
    - `recv`のエラー
- HTTPリクエストの解析に関するエラー
    - リクエストの本文の長さを特定できない
    - `chunked`において不正な`chunk`を受信した
    - セキュリティ上受け取ってはいけなさそうな内容を受信した

**Comment by ryo-manba** [comment]
TELNETで挙動を確認する

**Comment by corvvs** [comment]
`extra_data_buffer`に溜めたデータを再注入する処理についての考察が甘かった。

**Comment by corvvs** [comment]
回復可能なエラーについての定義を変えた。
平たく言うと

- リクエストをルーティングするまでに発生した`minor_error`
- ルーティング(=リクエストマッチング)で発生した`minor_error`

だけが回復可能で、それ以外は全部回復不可能とする。

**Comment by corvvs** [comment]
これなら実装はそれほど難しくないと思う。
