### ISSUE TITLE
2022-07-24 MTGで共有したいこと

### ISSUE THREAD

**Issue by ryo-manba** [corvvs/webserv#86]

**Comment by ryo-manba** [comment]
## rmatsuka
- [ ] configのdefault_server対応の実装
- [ ] configの継承バグの原因
- [ ] configのgoogletestの実装

**Comment by corvvs** [comment]
## yokawada

- [ ] CGIのプルリク出した
- [ ] CGIスクリプトの異常終了をどうするか
- [ ] CGIスクリプトの存在・実行可能性チェック方法
