### ISSUE TITLE
Conf - RoundTrip連携 (ルーティング)

### ISSUE THREAD

**Issue by corvvs** [corvvs/webserv#91]
## ルーティングとは

改めて定義しておく。
ルーティングは「リクエストからオリジネータを生成する処理」のことを指す。

### 必要な情報

- 最低限
  - リクエストのメソッド
  - リクエストのURL
    - 主にリクエストターゲットのこと
  - リクエスト先ホスト
  - サーバポート

### 処理

1. リクエスト先ホストとサーバポートから, ルーティング対象となる`server`ブロックを決定する
2. リクエストがCGIをターゲットにしているなら, リクエストがCGIスクリプトにマッチするかどうかを判定する
    - 存在しないなら404
3. リクエストURL(とリクエストのメソッド)から`server`ブロック内の`location`に対するマッチングを行う
    - 存在しないなら404
    - メソッドが許可されていないなら405
4. マッチング結果をもとに、オリジネータが生成可能なら適切な種類のオリジネータを生成する

1から3までを**リクエストマッチング**と呼ぶのはどうか。

### 結果

「オリジネータ生成のために必要な情報」のうち、Confに依存しているもの。

- 対象ファイルを特定するファイルパス
- CGIかどうか

他なんかあるか？

### オリジネータ種別

- [x] `Echoer`
- [x] `CGI` - CGIスクリプトを実行し, その応答をHTTP応答に変換する
- [ ] `FileReader` - リクエストされたリソース(ファイル)の内容を読み取り, HTTP応答に載せる - GETなど
- [ ] `FileWriter` - リクエストされたリソース(ファイル)にHTTP要求の内容を書き込む - POST, PUTなど
- [ ] `FileDeleter` - リクエストされたリソース(ファイル)を削除する - DELETE
- [ ] `AutoIndexer` - オートインデックスにおいて表示されるHTMLページを作る - GETだけ?
- (`Proxy`)

### その他
関連issue https://github.com/corvvs/webserv/issues/42

**Comment by ryo-manba** [comment]
やるで

**Comment by corvvs** [comment]
リクエストターゲットを表現する構造体を作った:

cf. https://datatracker.ietf.org/doc/html/rfc3986#section-3

```c++
struct RequestTarget {
    typedef HTTP::light_string light_string;

    // リクエストの"form"
    // - origin-form: "/"から始まるパスだけのやつ
    // - authority-form: ドメイン部だけのやつ
    // - absolute-form: URLまるごと
    // - asterisk-form: "*"のみ
    enum t_form { FORM_UNKNOWN, FORM_ORIGIN, FORM_AUTHORITY, FORM_ABSOLUTE, FORM_ASTERISK };

    // 与えられたリクエストターゲット
    const light_string given;
    // エラーかどうか
    bool is_error;
    // 何formか
    t_form form;

    //     foo://example.com:8042/over/there?name=ferret#nose
    //     \_/   \______________/\_________/ \_________/ \__/
    //     |           |            |            |        |
    // scheme     authority       path        query   fragment
    //     |   _____________________|__
    //     / \ /                        \
    //     urn:example:animal:ferret:nose

    light_string scheme;
    light_string authority;
    light_string path;
    light_string query;

    RequestTarget(const light_string &target);
};
```

**Comment by ryo-manba** [comment]
`scheme` のバリデーションはルーティングで行う。
本来configに設定が書いてなかった場合に弾くため。

**Comment by ryo-manba** [comment]
最終的に、 `Router`は `RoundTrip` に error_page の設定などconfの情報を渡すことになる。
その情報を元に `RoundTrip` は処理する。

処理フロー
1. error_pageの設定がある
2. エラー発生
3. RoundTripより下で例外を投げる(ここにconfの情報を渡せれば、4にその情報を伝播することもできるはず)
4. Connectionがキャッチする

**Comment by ryo-manba** [comment]
ディレクトリトラバーサルはルーターが見る必要がある。(例外を投げる)
```
http:/localhost:8080/../../../
```

**Comment by ryo-manba** [comment]
curlの場合パスの正規化が行われてるっぽいので、テストするときはTELNETを使う必要がありそう。
```
> curl localhost:80/../../hoge -v
*   Trying 127.0.0.1:80...
* Connected to localhost (127.0.0.1) port 80 (#0)
> GET /hoge HTTP/1.1
> Host: localhost
> User-Agent: curl/7.77.0
> Accept: */*
```

**Comment by ryo-manba** [comment]
> リクエストターゲットを表現する構造体を作った:

Hostの情報も必要ですね。
listenが複数コンテキストで定義されていた場合に使うので。

**Comment by corvvs** [comment]
Hostはヘッダとして与えられる(`Host:`)と考えたほうがよさそうなので、少し違った名前で追加します。

**Comment by ryo-manba** [comment]
PATH_INFOの判定
左からターゲットを読んでいき、実行権限があるファイルが見つかったらそれ以降をPATH_INFOにする。

**Comment by corvvs** [comment]
連携用インターフェース

```c++
struct RequestMatchingResult {

    typedef std::map< HTTP::t_status, HTTP::byte_string > status_dict_type;

    // CGIかどうか
    bool is_cgi;
    // リクエストターゲットにマッチしたローカルファイルのパス
    // CGIでいう`SCRIPT_NAME`に相当
    HTTP::byte_string local_path;
    // リクエストターゲットのうち local_path より後の部分
    // CGIでいう`PATH_INFO`に相当
    HTTP::byte_string after_path;

    // あるHTTPステータスの時はこのファイルの中身を返す, という時の
    // ステータスとファイルパスの辞書.
    status_dict_type status_page_dict;
};

class IRequestMatcher {
public:
    ~IRequestMatcher() {}

    virtual RequestMatchingResult request_match(const RequestHTTP &request) = 0;
};
```

`IRequestMatcher`を実装したクラスを作ってほしいです @ryo-manba
